spring:
  profiles:
    active: dev
    include:
      - filter
      - jwt
      - mail
      - notification

  jpa:
    open-in-view: false

  devtools:
    restart:
      enabled: true